### ISSUE TITLE
Closing/Disposing database throws Exception because of unfinished replicators

### ISSUE THREAD

**Issue by thomai-d** [couchbase/couchbase-lite-net#1020]
See the following code:
![db](https://user-images.githubusercontent.com/24974298/39322063-f305d886-4988-11e8-97c9-7b35c65e072a.png)

The `Close()` call throws an exception if a replicator has been started:

```
Couchbase.Lite.CouchbaseLiteException
  HResult=0x80131500
  Message=CouchbaseLiteException (LiteCoreDomain / 16): Cannot close the database. Please stop all of the replicators before closing the database..
  Source=Couchbase.Lite
  StackTrace:
   at Couchbase.Lite.Database.ThrowIfActiveItems()
   at Couchbase.Lite.Database.<Dispose>b__93_0()
   at Couchbase.Lite.Support.ThreadSafety.DoLocked(Action a)
   at Couchbase.Lite.Database.Dispose()
   at Couchbase.Lite.Database.Close()
   at TestApp.Service.CouchbaseDatabase..ctor() in ...\CouchbaseDatabase.cs:line 75
```

The replicator server is down and the following snippet is the only couchbase code that is executed in my testing application. The exception is raised on Android as well as on UWP.

### Library Version
2.0.0.1

### .NET Runtime
Xamarin Android v27.0.2
Microsoft.NETCore.UniversalWindowsPlatform v6.0.8

### Operating System / Device Details
Android OS 6.01
Windows 10 Version 1709

### Log Output
[log-1524763742.zip](https://github.com/couchbase/couchbase-lite-net/files/1952308/log-1524763742.zip)

### Expected behavior
`this.db.Close()` as well as `this.db.Dispose()` can be called without causing an exception.

### Actual behavior
`this.db.Close()` as well as `this.db.Dispose()` throws an exception when a replicator is configured.

### Steps To Reproduce
Execute given code:
    this.db = new Database(DatabaseName);
    var targetEndpoint = new URLEndpoint(new Uri("ws://192.168.0.11:4984/app"));
    var replConfig = new ReplicatorConfiguration(this.db, targetEndpoint);
    replConfig.Authenticator = new BasicAuthenticator("GUEST", "");
    replConfig.Continuous = true;
    this.replicator = new Replicator(replConfig);
    this.replicator.Start();
    this.replicator.Stop();
    this.replicator.Dispose();
    this.db.Close();

**Comment by borrrden** [comment]
Calling Stop on the replicator is not a synchronous function so you must wait for the status to change to stopped. After that you can close the database. Let me know if that helps.

**Comment by thomai-d** [comment]
This won't help:

Looking at the sourecode I think the problem is that the Replicator.Status.Activity won't change to Stop.


            this.db = new Database(DatabaseName);
            var targetEndpoint = new URLEndpoint(new Uri("ws://192.168.0.11:4984/app"));
            var replConfig = new ReplicatorConfiguration(this.db, targetEndpoint);
            replConfig.Authenticator = new BasicAuthenticator("GUEST", "");
            replConfig.Continuous = true;
            this.replicator = new Replicator(replConfig);
            Debug.WriteLine($"Before Start: {this.replicator.Status.Activity}");
            this.replicator.Start();
            Debug.WriteLine($"After Start: {this.replicator.Status.Activity}");
            this.replicator.Stop();
            Debug.WriteLine($"After Stop: {this.replicator.Status.Activity}");

            for (int n = 1; n <= 6; n++)
            {
                Thread.Sleep(10000);
                Debug.WriteLine($"After {n*10} seconds: {this.replicator.Status.Activity}");
            }

            this.replicator.Dispose();
            this.db.Close();

Will produce an output of:

```
Before Start: Stopped
After Start: Connecting
After Stop: Connecting
After 10 seconds: Busy
After 20 seconds: Busy
After 30 seconds: Busy
After 40 seconds: Busy
After 50 seconds: Busy
After 60 seconds: Busy
Exception thrown: 'Couchbase.Lite.CouchbaseLiteException' in Couchbase.Lite.dll
CouchbaseLiteException (LiteCoreDomain / 16): Cannot close the database. Please stop all of the replicators before closing the database..
```

Again, this behavior is only seen if the sync gateway is offline. 
If the server is up, the state will change to "Stop" within a second and Disposing/Stopping is no problem.

**Comment by borrrden** [comment]
For Xamarin this sounds like #1000 but I haven't heard of this happening on UWP yet.

**Comment by borrrden** [comment]
FYI the fixes for that and other Xamarin replication issues are containing in the newest DB (2.1.0-db001)

**Comment by borrrden** [comment]
Has the new DB cleared this up @thomai-d ?

**Comment by thomai-d** [comment]
2.1.0-db001 on UWP is still buggy.

Two cases:

1. If I set the replicator to a nonexisting IP in the LAN, the replication state will hang in "Connecting" even if I call stop and wait for a long time. Calling database.Delete() will result in the same exception as above.

2. If I set the replicator to a nonexisting IP in the Internet, the replication state will be "Stopped" but calling database.Delete() will also result in the exception.
