### ISSUE TITLE
ChangeEncryptionKey method is throwing exception when changing key for DB

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1044]
### .NET Runtime
.NET Core 2.1.0-b0202

### Operating System / Device Details
Windows 10

### Log Output
[dotnet.log](https://github.com/couchbase/couchbase-lite-net/files/2211121/dotnet.log)

### Expected behaviour
Method call should run without any exception.

### Actual behavior
Getting below exception - 
e	{Couchbase.Lite.CouchbaseLiteException: CouchbaseLiteException (LiteCoreDomain / 7): No such file or directory.
   at LiteCore.Interop.NativeHandler.ThrowOrHandle() in C:\Jenkins\workspace\couchbase-lite-net-edition-build\couchbase-lite-net-ee\couchbase-lite-net\src\LiteCore\src\LiteCore.Shared\Interop\NativeHandler.cs:line 261
   at LiteCore.Interop.NativeHandler.Execute(C4TryLogicDelegate1 block) in C:\Jenkins\workspace\couchbase-lite-net-edition-build\couchbase-lite-net-ee\couchbase-lite-net\src\LiteCore\src\LiteCore.Shared\Interop\NativeHandler.cs:line 188
   at Couchbase.Lite.Support.ThreadSafety.DoLockedBridge(C4TryLogicDelegate1 a) in C:\Jenkins\workspace\couchbase-lite-net-edition-build\couchbase-lite-net-ee\couchbase-lite-net\src\Couchbase.Lite.Shared\Support\ThreadSafety.cs:line 61
   at Couchbase.Lite.Testing.DatabaseMethods.<>c__DisplayClass8_0.<DatabaseChangeEncryptionKey>b__0(Database db) in C:\Users\Administrator\Desktop\mobile-testkit\CBLClient\Apps\CBLTestServer-Dotnet\TestServer\DatabaseMethods.cs:line 153
   at Couchbase.Lite.Testing.DatabaseMethods.With[T](IReadOnlyDictionary`2 postBody, String key, Action`1 action) in C:\Users\Administrator\Desktop\mobile-testkit\CBLClient\Apps\CBLTestServer-Dotnet\TestServer\DatabaseMethods.cs:line 51
   at Couchbase.Lite.Testing.DatabaseMethods.DatabaseChangeEncryptionKey(NameValueCollection args, IReadOnlyDictionary`2 postBody, HttpListenerResponse response) in C:\Users\Administrator\Desktop\mobile-testkit\CBLClient\Apps\CBLTestServer-Dotnet\TestServer\DatabaseMethods.cs:line 145
   at Couchbase.Lite.Testing.Router.Handle(Uri endpoint, Stream body, HttpListenerResponse response) in C:\Users\Administrator\Desktop\mobile-testkit\CBLClient\Apps\CBLTestServer-Dotnet\TestServer\Router.cs:line 273}	System.Exception {Couchbase.Lite.CouchbaseLiteException}

### Steps To Reproduce
run the below command -
 pytest -rsx -s --mode=cc --server-version=5.5.0-2473 --sync-gateway-version=2.1.0-107 --no-conflicts --timeout=3600 --xattrs --skip-provisioning --liteserv-version=2.1.0-193 --liteserv-host=localhost --liteserv-port=8080 --liteserv-platform=net-msft --create-db-per-test=cbl-test --no-conflicts --create-db-per-suite=suite-test -k test_databaseEncryption testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_database.py

### Reproduction Project

git clone https://github.com/couchbaselabs/mobile-testkit.git
git checkout feature/diff-cbl20-master

**Comment by borrrden** [comment]
This issue was moved to couchbase/couchbase-lite-core#540
