### ISSUE TITLE
SDK fails for opening Database files over 2GB

### ISSUE THREAD

**Issue by badavid85** [couchbase/couchbase-lite-net#1197]
### Library Version
CouchbaseLite/2.6.0 (.NET; Microsoft Windows 10.0.18363) Build/129 LiteCore/2.6.0 (2193) Commit/e715812a

### .NET Runtime
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

### Operating System / Device Details
Microsoft Windows 10.0.18363

### Log Output

2019-12-10 10:56:27.098-06:00 [1]| INFO)  [Database] (Startup) [1] CouchbaseLite/2.6.0 (.NET; Microsoft Windows 10.0.18363) Build/129 LiteCore/2.6.0 (2193) Commit/e715812a
2019-12-10 10:57:34.610-06:00 [1]| INFO)  [Database] (Database) [1] Opening database at C:\Users\Bruno\source\repos\CouchbaseLiteReader\CouchbaseLiteReader\bin\x64\Debug\netcoreapp3.0\CouchbaseLite\testDatabase.cblite2

### Expected behavior
Couchbase Lite SDK should be able to work with database files larger than 2GB.

### Actual behavior
Exception is thrown when opening the database.

Couchbase.Lite.CouchbaseLiteException: CouchbaseLiteException (LiteCoreDomain / 21): file/data is not in the requested format.
   at LiteCore.Interop.NativeHandler.ThrowOrHandle()
   at LiteCore.Interop.NativeHandler.Execute(C4TryLogicDelegate2 block)
   at LiteCore.LiteCoreBridge.Check(C4TryLogicDelegate2 block)
   at Couchbase.Lite.Database.<>c__DisplayClass91_0.<Open>b__0()
   at Couchbase.Lite.Support.ThreadSafety.DoLocked(Action a)
   at Couchbase.Lite.Database.Open()
   at Couchbase.Lite.Database..ctor(String name, DatabaseConfiguration configuration)
   at CouchbaseLiteReader.Program.Main(String[] args) in C:\Users\Bruno\source\repos\CouchbaseLiteReader\CouchbaseLiteReader\Program.cs:line 23

### Steps To Reproduce

1. Run attached project
1.1. It fails if loopCount variable is equal to 2400 (Database generated will be around 3GB)
1.2. It works fine if loopCount variable is equal to 1400 (Database generated will be around 1.5GB)

### Reproduction Project

[CouchbaseLiteReader.zip](https://github.com/couchbase/couchbase-lite-net/files/3946195/CouchbaseLiteReader.zip)

**Comment by borrrden** [comment]
Great find!  Migrated to [CBL-579](https://issues.couchbase.com/browse/CBL-579)

**Comment by badavid85** [comment]
Hi @borrrden, any idea of when this bug would be fixed? We have a few users that are pretty close to reaching the 2GB database size.

**Comment by borrrden** [comment]
It is scheduled for 2.7.1 (the next release after 2.7.0).  I think this is also being communicated by other channels, in which case those should take priority.

**Comment by NgyAnthony** [comment]
Issue fixed, should be closed [CBL-579](https://issues.couchbase.com/browse/CBL-579)

**Comment by Sandychuang8** [comment]
Issue is fixed in the later release.
