### ISSUE TITLE
LiteCore.dll not found for WinUI3/Project Reunion app (.NET 5)

### ISSUE THREAD

**Issue by mlynch** [couchbase/couchbase-lite-net#1311]
I'm assuming that this library does not yet support WinUI3/Project Reunion projects, but since there's no mention of it anywhere I wanted to post this issue to see whether that is actually the case or perhaps I'm doing something wrong.

It seems like the search path for the `LiteCore.dll` is not correct when using `NetDesktop`, and the `UWP` support library doesn't compile under the .NET 5 target.

I do see `LiteCore.dll` listed as both a dependency in my project, and also on disk. However, it's one folder deeper in a specific `net5.0-windows10.0.19041` folder in `bin/Debug` which is not on the dll search path as shown in the errors below.

I'm just looking for some indication as to whether this is expected not to work and whether I should consider dropping WinUI3 for the time being since it's more important that I get this library working than use WinUI3.

### Library Version

Couchbase.Lite.Enterprise 2.8.6

### .NET Runtime

.NET 5.0-windows10.0.19041

### Operating System / Device Details

Windows 10 10.0.19042 Build 19042

### Log Output

```
System.TypeInitializationException: The type initializer for 'Couchbase.Lite.Database' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'LiteCore.Interop.Native' threw an exception.
 ---> System.DllNotFoundException: Could not find LiteCore.dll!  Nothing is going to work!
Tried searching in:
F:\GitHub\enterprise-couchbase-lite-test\example\windows\App\App\App (Package)\bin\x86\Debug\runtimes\win7-x86\native\LiteCore.dll
F:\GitHub\enterprise-couchbase-lite-test\example\windows\App\App\App (Package)\bin\x86\Debug\AppX\App\x86\LiteCore.dll
F:\GitHub\enterprise-couchbase-lite-test\example\windows\App\App\App (Package)\bin\x86\Debug\AppX\App\bin\x86\LiteCore.dll

   at Couchbase.Lite.Support.NetDesktop.LoadLiteCore()
   at LiteCore.Interop.Native..cctor()
   --- End of inner exception stack trace ---
   at LiteCore.Interop.Native.c4log_getDomain(Byte* name, Boolean create)
   at Couchbase.Lite.Logging.FileLogger.SetupDomainObjects()
   at Couchbase.Lite.Logging.FileLogger..ctor()
   at Couchbase.Lite.Logging.Log..ctor()
   at Couchbase.Lite.Database..cctor()
   --- End of inner exception stack trace ---
   at Couchbase.Lite.Database..ctor(String name, DatabaseConfiguration configuration)
   at CouchbaseLiteTest.CouchbaseLiteTest.Open()
```

### Expected behavior

`LiteCore.dll` should be found

### Actual behavior

`LiteCore.dll` is not found. 

### Steps To Reproduce

`. [Create an app](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?tabs=desktop-csharp) using WinUI3
2. Install Couchbase.Lite library and one of the support libraries (the only one I could get to compile for this .NET 5 target is `NetDesktop`)
3. Create a small couchbase lite app and run it, this error will be thrown

**Comment by borrrden** [comment]
Not expected, but not surprising that it does not work.  It has never been tried or tested on this side, you may be the first one.  The fix would be to include that in the search path for the NetDesktop nuget package, but unless the runtime will construct it for us it's going to be a chore to do introspection to get the actual correct name.  As a workaround, could you copy the file to one of the expected locations during your build?

**Comment by mlynch** [comment]
Wow, quick response! I was incorrect about where `LiteCore.dll` was in relation to the search path, it was actually in `App\App\App (Package)\bin\x86\Debug\AppX\App` but the search path is expecting another `x86` or `bin\x86` directory(s) in that `App` folder.

I just tried creating an `x86` directory in there and putting in `LiteCore.dll` into it and it appears to be working! 

Not sure how to automate this but at least this is a path forward for now and I don't feel like such an idiot for going with WinUI3 😅

**Comment by borrrden** [comment]
Out of curiosity, do you have a specific need for the x86 variant or would x64 do?  I find it odd that Microsoft keeps x86 around and for the C platform we're just outright not going to support it, which I feel would be a good idea to do here.

Aside from that the path that has been constructed here looks suspiciously like a UWP app and I kind of wonder if WinUI 3 is the first step of silently brushing UWP under the carpet a la Windows 8.x.

**Comment by mlynch** [comment]
Yea the x86 was just the default, I don't need it.

Looking at the search paths again, looks like the most straight-forward change is the `runtimes` folder has moved into the `AppX\Target` directory:

`F:\GitHub\enterprise-couchbase-lite-test\example\windows\App\App\App (Package)\bin\x64\Debug\AppX\App\runtimes\win7-x64\native`

Anyways, I don't know much about the underlying differences between WinUI3 and UWP but everything I've gathered so far suggests UWP is a dead end and this is the future (also the move to call the Project Reunion stuff the [Windows App SDK](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/) is pretty significant I think).
