### ISSUE TITLE
NullReferenceException when trying to call SetCookie on a Replication object from a C# console application

### ISSUE THREAD

**Issue by elevine** [couchbase/couchbase-lite-net#372]
I am trying to write a C# console application to do some testing with a sync gateway using custom authentication.  After getting the session information from the gateway, I do the following in my program:

```csharp
var auth = AuthenticatorFactory.CreateBasicAuthenticator(username, password);
_pushReplication.Authenticator = auth;
DateTime cookieExpiresDateTime = DateTime.Parse(cookieExpires); 
_pushReplication.SetCookie(cookieName, sessionId, "/", cookieExpiresDateTime, false, false);  
```

The last line results in a NullReferenceException.  It seems that the problem stems from the following line in the CookieStore constructor:

```csharp
  cookiesField = typeof(CookieContainer)
				.GetField("cookies", (BindingFlags.GetField | BindingFlags.Instance | BindingFlags.NonPublic));
```

The reflection being done there always returns null for cookiesField.  Here is the stack trace from the exception:  

```csharp
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Couchbase.Lite
  StackTrace:
       at Couchbase.Lite.Util.CookieStore.SerializeToDisk()
       at Couchbase.Lite.Util.CookieStore.Save()
       at Couchbase.Lite.Util.CookieStore.Add(CookieCollection cookies)
       at Couchbase.Lite.Support.CouchbaseLiteHttpClientFactory.AddCookies(CookieCollection cookies)
       at Couchbase.Lite.Replication.SetCookie(String name, String value, String path, DateTime expirationDate, Boolean secure, Boolean httpOnly)
       at CouchbaseConsole.MessageRepository.InitReplication(String databaseUrl, String username, String password, String cookieName, String sessionId, String cookieExpires) in c:\Users\eric.levine\Documents\Visual Studio 2013\Projects\CouchbaseTest\CouchbaseConsole\MessageRepository.cs:line 37
       at CouchbaseConsole.Program.Main(String[] args) in c:\Users\eric.levine\Documents\Visual Studio 2013\Projects\CouchbaseTest\CouchbaseConsole\Program.cs:line 34
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by elevine** [comment]
I tried running the same code on a Xamarin Android app and did not get the exception.  Maybe this is due to a difference between how CookieContainer is implemented in Mono vs Microsoft's .Net.

**Comment by zgramana** [comment]
@elevine Looks like I failed to bring over [this patch from our `windows-targets` branch](https://github.com/couchbase/couchbase-lite-net/blob/windows-targets/src/Couchbase.Lite.Shared/Util/CookieStore.cs).

I'm committing up a better refactored patch instead.

**Comment by elevine** [comment]
This fix seems to work the first time you set the cookie, but there is an exception when trying to load the CookieStore from the serialized JSON that was saved to disk.  It seems like the issue might be caused by extra fields existing in the JSON and Json.Net isn't ignoring them.

Here is the stack trace:

```csharp
{"Additional text found in JSON string after finishing deserializing object."}
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Couchbase.Lite.Util.CookieStore.DeserializeFromDisk() in c:\Users\eric.levine\Documents\GitHub\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\CookieStore.cs:line 193
   at Couchbase.Lite.Util.CookieStore..ctor(String directory) in c:\Users\eric.levine\Documents\GitHub\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\CookieStore.cs:line 74
   at Couchbase.Lite.Manager..ctor(DirectoryInfo directoryFile, ManagerOptions options) in c:\Users\eric.levine\Documents\GitHub\couchbase-lite-net\src\Couchbase.Lite.Shared\Manager.cs:line 176
   at Couchbase.Lite.Manager.get_SharedInstance() in c:\Users\eric.levine\Documents\GitHub\couchbase-lite-net\src\Couchbase.Lite.Shared\Manager.cs:line 96
   at CouchbaseConsole.MessageRepository..ctor(String databaseName) in c:\Users\eric.levine\Documents\GitHub\couchbase-lite-net\src\SyncTester\MessageRepository.cs:line 24
   at SyncTester.Program.Main(String[] args) in c:\Users\eric.levine\Documents\GitHub\couchbase-lite-net\src\SyncTester\Program.cs:line 36
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This is the contents of my cookies.json file:

```json
{
    ".localhost": {
        "Count": 1,
        "Values": [
            "[{\"Comment\":\"\",\"CommentUri\":null,\"HttpOnly\":false,\"Discard\":false,\"Domain\":\"localhost\",\"Expired\":false,\"Expires\":\"2015-01-27T10:04:46.0051479-05:00\",\"Name\":\"SyncGatewaySession\",\"Path\":\"/\",\"Port\":\"\",\"Secure\":false,\"TimeStamp\":\"2015-01-26T10:05:06.4099871-05:00\",\"Value\":\"2e3af70ae1d85f24a9ac170dc913c08c0a94371b\",\"Version\":0}]"
        ],
        "SyncRoot": {}
    }
}
```

**Comment by elevine** [comment]
@zgramana  I stepped through the code and see that the CookieCollectionJsonConverter.ReadJson method winds up returning null as a result of these lines: 

```csharp
var value = (string)reader.Value;
if (value == null)
{
    return null;
}
```

**Comment by zgramana** [comment]
@elevine that's for the feedback. I just ran the CookieStore unit tests and confirmed they failed. We'll get that fixed.

**Comment by borrrden** [comment]
It seems that Mono and .NET serialize these differently.  I guess that's the peril of leaving it up to the runtime.  I'll change it to serialize deterministically.

**Comment by elevine** [comment]
Are there any plans to release an update nuget package with this fix?

**Comment by borrrden** [comment]
The next release, 1.1, will include this fix. It should be coming in the next few weeks.
