### ISSUE TITLE
Compacting a database with attachments throws exception

### ISSUE THREAD

**Issue by ThomasWeiss** [couchbase/couchbase-lite-net#385]
I'm testing CouchBase.Lite 1.0.4.1 with CouchDB 1.6.1 as the backend.

Scenario:
* Create a doc on the backend
* Start a one-shot pull replication on the client, wait for its completion
```cs
while (replication.IsRunning)
{
    Thread.Sleep(1000);
}
```
* Compact the database -> OK
* Add an attachment to the doc on the backend
* Replicate on the client in the same fashion
* Compact the database -> `NullReferenceException` with the following stack trace:

```
at Sharpen.Arrays.Equals[T](T[] a1, T[] a2)
at Couchbase.Lite.BlobKey.Equals(Object o)
at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
at System.Collections.Generic.List`1.Contains(T item)
at Couchbase.Lite.BlobStore.DeleteBlobsExceptWithKeys(IList`1 keysToKeep)
at Couchbase.Lite.Database.GarbageCollectAttachments()
at Couchbase.Lite.Database.Compact()
at CouchbaseLiteDebug.Program.Main(String[] args) in c:\Users\Thomas\Documents\Visual Studio 2013\Projects\CouchbaseLiteDebug\CouchbaseLiteDebug\Program.cs:line 24
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by borrrden** [comment]
I believe this has been fixed at this point (I noticed that 1.0.4 crashes here and 1.1 does not)
