### ISSUE TITLE
Missing a null check in Custome Logger 

### ISSUE THREAD

**Issue by SunilDhaker** [couchbase/couchbase-lite-net#439]
Relevant Log : 

   Couchbase.Lite.Shared\Util\CustomLogger.cs:line 170
   at Couchbase.Lite.Util.Log.E(String tag, String msg, Exception tr) in c:\Users\  user\Desktop\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\Log.cs:line 316
   at Couchbase.Lite.Replication.set_LastError(Exception value) in c:\Users\  user\Desktop\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication.cs:line 1847
   at Couchbase.Lite.Replication.Retry() in c:\Users\  user\Desktop\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication.cs:line 1625
   at Couchbase.Lite.Replication.RetryIfReady() in c:\Users\  user\Desktop\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication.cs:line 1641
   at Couchbase.Lite.Replication.<ScheduleRetryIfReady>b__32(Task task) in c:\Users\  user\Desktop\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication.cs:line 1668
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

In This 

``` 
public void E (string tag, string msg, Exception tr)
       {
            if (!(level.HasFlag(SourceLevels.Error)))
                return;
            lock (locker){ ts.Fail("{0}: {1}".Fmt(tag, msg), Flatten(tr).ToString()); }
        }
```

Adding a breakpoint showing tr is null .  So I think there should be a null check there . Also Other methods in this file should have this check I think  :|

**Comment by SunilDhaker** [comment]
Also one More Frequent Exception I am getting is in Change tracker : 


 ChangeTracker: Exception in change tracker
    System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.WebException: The operation has timed out.
       at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
       at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       --- End of inner exception stack trace ---
       at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.StreamReader.ReadBuffer()
       at System.IO.StreamReader.ReadLine()
       at Couchbase.Lite.Replicator.ChangeTracker.ChangeFeedResponseHandler(Task`1 responseTask) in c:\Users\rbauser\Desktop\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication\ChangeTracker.cs:line 465
       at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()

**Comment by borrrden** [comment]
Actually I noticed the missing null checks today myself as well.  I'll add those soon.  However, please refrain from adding separate problems onto the same ticket.  It makes things difficult to track.
