### ISSUE TITLE
Error on attachments with digest as MD5

### ISSUE THREAD

**Issue by reyalpsirc** [couchbase/couchbase-lite-net#442]
According to couchdb [docs](http://docs.couchdb.org/en/latest/api/document/common.html), the attachments "digest" property is set as MD5 but, from what I saw, the code seems to only support SHA1 now? Is there any way to make the old MD5 attachments to work?

Because currently, when I update a document while my Xamarin project is running, I get the following replication from the replication code:

    Database: System.ArgumentException: md5-ravv2WuyJ0c93JdlR6qNUA== did not start with sha1-
        at Couchbase.Lite.BlobKey.DecodeBase64Digest (System.String base64Digest) [0x0001c] in <filename unknown>:0 
        at Couchbase.Lite.BlobKey..ctor (System.String base64Digest) [0x00000] in <filename unknown>:0 
        at Couchbase.Lite.Internal.AttachmentInternal..ctor (System.String name, IDictionary`2 info) [0x00050] in <filename unknown>:0 
        at Couchbase.Lite.Database+<ProcessAttachmentsForRevision>c__AnonStorey8.<>m__0 (System.String name, IDictionary`2 attachInfo) [0x00002] in <filename unknown>:0 
        at Couchbase.Lite.Internal.RevisionInternal.MutateAttachments (System.Func`3 mutator) [0x00065] in <filename unknown>:0 
        at Couchbase.Lite.Database.ProcessAttachmentsForRevision (Couchbase.Lite.Internal.RevisionInternal rev, System.String prevRevId, Couchbase.Lite.Status status) [0x000a1] in <filename unknown>:0 
        at Couchbase.Lite.Database+<ForceInsert>c__AnonStorey1.<>m__0 () [0x00229] in <filename unknown>:0 
        at Couchbase.Lite.Database+<RunInTransaction>c__AnonStorey0.<>m__0 () [0x0000e] in <filename unknown>:0 
            System.ArgumentException: md5-ravv2WuyJ0c93JdlR6qNUA== did not start with sha1-
                at Couchbase.Lite.BlobKey.DecodeBase64Digest (System.String base64Digest) [0x0001c] in <filename unknown>:0 
                at Couchbase.Lite.BlobKey..ctor (System.String base64Digest) [0x00000] in <filename unknown>:0 
                at Couchbase.Lite.Internal.AttachmentInternal..ctor (System.String name, IDictionary`2 info) [0x00050] in <filename unknown>:0 
                at Couchbase.Lite.Database+<ProcessAttachmentsForRevision>c__AnonStorey8.<>m__0 (System.String name, IDictionary`2 attachInfo) [0x00002] in <filename unknown>:0 
                at Couchbase.Lite.Internal.RevisionInternal.MutateAttachments (System.Func`3 mutator) [0x00065] in <filename unknown>:0 
                at Couchbase.Lite.Database.ProcessAttachmentsForRevision (Couchbase.Lite.Internal.RevisionInternal rev, System.String prevRevId, Couchbase.Lite.Status status) [0x000a1] in <filename unknown>:0 
                at Couchbase.Lite.Database+<ForceInsert>c__AnonStorey1.<>m__0 () [0x00229] in <filename unknown>:0 
                at Couchbase.Lite.Database+<RunInTransaction>c__AnonStorey0.<>m__0 () [0x0000e] in <filename unknown>:0 
    Puller: Exception inserting revisions
            System.ArgumentException: md5-ravv2WuyJ0c93JdlR6qNUA== did not start with sha1-
                at Couchbase.Lite.BlobKey.DecodeBase64Digest (System.String base64Digest) [0x0001c] in <filename unknown>:0 
                at Couchbase.Lite.BlobKey..ctor (System.String base64Digest) [0x00000] in <filename unknown>:0 
                at Couchbase.Lite.Internal.AttachmentInternal..ctor (System.String name, IDictionary`2 info) [0x00050] in <filename unknown>:0 
                at Couchbase.Lite.Database+<ProcessAttachmentsForRevision>c__AnonStorey8.<>m__0 (System.String name, IDictionary`2 attachInfo) [0x00002] in <filename unknown>:0 
                at Couchbase.Lite.Internal.RevisionInternal.MutateAttachments (System.Func`3 mutator) [0x00065] in <filename unknown>:0 
                at Couchbase.Lite.Database.ProcessAttachmentsForRevision (Couchbase.Lite.Internal.RevisionInternal rev, System.String prevRevId, Couchbase.Lite.Status status) [0x000a1] in <filename unknown>:0 
                at Couchbase.Lite.Database+<ForceInsert>c__AnonStorey1.<>m__0 () [0x00229] in <filename unknown>:0 
                at Couchbase.Lite.Database+<RunInTransaction>c__AnonStorey0.<>m__0 () [0x0000e] in <filename unknown>:0

**Comment by borrrden** [comment]
Do you mean that you have pre-existing documents with the md5 style digest in your local database?

**Comment by reyalpsirc** [comment]
Yes, exactly.

**Comment by borrrden** [comment]
Ah, in that case the current version will not handle them correctly.  I'll switch it to deal with legacy documents gracefully.  It shouldn't take much time.

**Comment by reyalpsirc** [comment]
Thank you! =)

**Comment by borrrden** [comment]
Let me confirm the flow here.  This happens when you are running Couchbase Lite with a continuous pull replication from a CouchDB server instance?

**Comment by reyalpsirc** [comment]
Yes, that's it. Forgot to mention that.

**Comment by borrrden** [comment]
@reyalpsirc I've been able to reproduce and correct the issue.  However, in the process I've found another problem so after I finish looking into that I will commit a fix.

**Comment by borrrden** [comment]
@reyalpsric Alright, it's in.  Here is a rundown of the test I set up to check this since it is quite long.

1) Create 3 revisions on a legacy document by by passing the Couchbase Lite API (the API won't allow it, and this simulates having documents already existing)

2) Create identical documents on CouchDB

3) Setup a continuous pull replication and start it.  

4) Create a new revision on the server, which doesn't change the attachment.  Before the fix, the test would fail here with the error you describe.  

5) Delete the previous attachment on the server

6) Upload a new attachment to the server

The behavior is now that at step 4, the document will maintain its MD5 hash until the attachment is changed again.  At revision 6, the new document will have md5 on the server, but sha1 in the local database.

**Comment by reyalpsirc** [comment]
Hi @borrrden,

I was about to test this with your fix but now, once I run the app with the rebuilt library, I get this error:

	Java.Lang.RuntimeException: java.lang.reflect.InvocationTargetException
	    at --- End of managed exception stack trace ---
	    at java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	    at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	    at at dalvik.system.NativeStart.main(Native Method)
	    at Caused by: java.lang.reflect.InvocationTargetException
	    at at java.lang.reflect.Method.invokeNative(Native Method)
	    at at java.lang.reflect.Method.invoke(Method.java:511)
	    at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	    at ... 2 more
	    at Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.TypeInitializationException: An exception was thrown by the type initializer for Couchbase.Lite.Manager ---> System.ArgumentNullException: Argument cannot be null.
	    at Parameter name: stream
	    at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen) [0x00022] in <filename unknown>:0
	    at System.IO.StreamReader..ctor (System.IO.Stream stream, Boolean detectEncodingFromByteOrderMarks) [0x0000d] in <filename unknown>:0
	    at System.IO.StreamReader..ctor (System.IO.Stream stream) [0x00000] in <filename unknown>:0
	    at at (wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (System.IO.Stream)
	    at Couchbase.Lite.Manager..cctor () [0x0005a] in <filename unknown>:0
	    at --- End of inner exception stack trace ---
	    at at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
	    at at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0003b>
	    at at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () <IL 0x0000c, 0x00032>
	    at at Java.Lang.Thread/RunnableImplementor.Run () <IL 0x00011, 0x0004c>
	    at at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) <IL 0x0000a, 0x0005e>
	    at at (wrapper dynamic-method) object.c358d344-4d74-413a-a66a-fb54c9682fa4 (intptr,intptr) <IL 0x00011, 0x0001f>
	    at at mono.java.lang.RunnableImplementor.n_run(Native Method)
	    at at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	    at at android.os.Handler.handleCallback(Handler.java:725)
	    at at android.os.Handler.dispatchMessage(Handler.java:92)
	    at at android.os.Looper.loop(Looper.java:137)
	    at at android.app.ActivityThread.main(ActivityThread.java:5041)
	    at ... 5 more

Did anything changed on the way that `Manager` is called?

**Comment by reyalpsirc** [comment]
Thanks @borrrden =)

One last thing: I was about to try this out but now, It seems that I'm unable to build the repository on Xamarin:

/Users/cristianosantos/Downloads/couchbase-lite-net-c6a4fba3e1c2405e44d87891728ed907862a5671/src/Couchbase.Lite.Net45/Couchbase.Lite.Net45.csproj: Error: Command 'mono /Users/cristianosantos/Downloads/couchbase-lite-net-c6a4fba3e1c2405e44d87891728ed907862a5671/src/Couchbase.Lite.Net45/../../Tools/GitVersion/GitVersion.exe "/Users/cristianosantos/Downloads/couchbase-lite-net-c6a4fba3e1c2405e44d87891728ed907862a5671/src/Couchbase.Lite.Net45/../.." "/Users/cristianosantos/Downloads/couchbase-lite-net-c6a4fba3e1c2405e44d87891728ed907862a5671/src/Couchbase.Lite.Net45/../Couchbase.Lite.Shared/Properties/version"' exited with code: 1. (Couchbase.Lite.Net45)

So, I tried to run that command on the Terminal of my Mac and it gave the following:

	Unhandled Exception:
	System.NullReferenceException: Object reference not set to an instance of an object
	    at GitSharp.Ref.get_Target () [0x00000] in <filename unknown>:0 
	    at GitSharp.Branch.get_CurrentCommit () [0x00000] in <filename unknown>:0 
	    at GitVersion.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
	[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
	    at GitSharp.Ref.get_Target () [0x00000] in <filename unknown>:0 
	    at GitSharp.Branch.get_CurrentCommit () [0x00000] in <filename unknown>:0 
	    at GitVersion.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 

What am I missing here?

**Comment by reyalpsirc** [comment]
Ok, the problem was that I downloaded the repository as a ZIP file instead of git clone.

That should be added to the Readme file no?

**Comment by borrrden** [comment]
Was that the problem?!  Gosh, I would have never figured that out...

I will never ever ever ever trust GitHub to download a zip file correctly, and you should not either ^^;  I will add a glaring note in the README

**Comment by reyalpsirc** [comment]
Yeah, the .git folder is not included on the Zip file.
From now on, will only use git clone for that ;)

**Comment by borrrden** [comment]
Right, I suppose it wouldn't be...hmmmm but I suppose other people will try to download the zip as well, so in the meantime I will also fix the GitVersion program to handle that case as well as making a note in the README.

**Comment by reyalpsirc** [comment]
Yeah, might be better to do it.

Just one last thing that I'm not sure if I'm doing right: Each time I pull the repository and Rebuild the .Net45 project, I need to add the compiler directive `__MOBILE__` to the current configuration in order to run the DLL on my PCL project of Xamarin. Is this the correct way to do it or I should be doing it differently?

**Comment by borrrden** [comment]
We don't support PCL targets at this time (we will look into that once we get WinRT support finished, but that is going to take a while), so keep doing whatever you are doing if it is working.  There is no official right way right now, so there can't be a wrong one I guess.

**Comment by reyalpsirc** [comment]
Oh, ok. Then I should say that doing that change on the compiler directives of .Net45 has been working before.

Now I have a problem that I'm not sure if it is related with that:

	Java.Lang.RuntimeException: java.lang.reflect.InvocationTargetException
	    at --- End of managed exception stack trace ---
	    at java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	    at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	    at at dalvik.system.NativeStart.main(Native Method)
	    at Caused by: java.lang.reflect.InvocationTargetException
	    at at java.lang.reflect.Method.invokeNative(Native Method)
	    at at java.lang.reflect.Method.invoke(Method.java:511)
	    at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	    at ... 2 more
	    at Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.TypeInitializationException: An exception was thrown by the type initializer for Couchbase.Lite.Store.SqliteCouchStore ---> System.Exception: Something went wrong in the build configuration.    This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.    Reference the appropriate platform assembly instead.
	    at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_libversion () [0x00000] in <filename unknown>:0
	    at SQLitePCL.raw.sqlite3_libversion () [0x00000] in <filename unknown>:0
	    at Couchbase.Lite.Store.SqliteCouchStore..cctor () [0x00091] in <filename unknown>:0
	    at --- End of inner exception stack trace ---
	    at at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
	    at at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0003b>
	    at at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () <IL 0x0000c, 0x00032>
	    at at Java.Lang.Thread/RunnableImplementor.Run () <IL 0x00011, 0x0004c>
	    at at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) <IL 0x0000a, 0x0005e>
	    at at (wrapper dynamic-method) object.52e939e4-c0f6-4576-ba26-50ae151c059a (intptr,intptr) <IL 0x00011, 0x0001f>
	    at at mono.java.lang.RunnableImplementor.n_run(Native Method)
	    at at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	    at at android.os.Handler.handleCallback(Handler.java:725)
	    at at android.os.Handler.dispatchMessage(Handler.java:92)
	    at at android.os.Looper.loop(Looper.java:137)
	    at at android.app.ActivityThread.main(ActivityThread.java:5041)
	    at ... 5 more

Thanks for all the support =).

**Comment by borrrden** [comment]
This is outside the realm of support at the moment.  I think it's better to simply backpedal and set up shared projects if possible.  That is the current recommended way of making a multiplatform project.  For an example of that in use you can look at the Couchbase Connect app mentioned at the bottom of the README.

**Comment by reyalpsirc** [comment]
Ok, I've been able to run this by doing these steps:
* Add the __MOBILE__ compiler directive to .Net45
* Build and then add the DLL and all required dependencies to the PCL project
* Build the .Android version
* Add that DLL and all required dependencies to the Android project that uses the PCL

I did not test this yet with iOS project but, it should also need to be done as building the .iOS project and adding it and its dependencies to the iOS project that uses the PCL.

**Comment by reyalpsirc** [comment]
Sorry, its me again. Is the Android version of CouchBase working well? Because I'm having multiple errors like this:

    SqlitePCLRawStorageEngine: RawQuery sql: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1    AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ? (-1, 0)
    Database: Exception parsing json:
    Couchbase.Lite.CouchbaseLiteException: Database error: BadJson ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: *. Path '', line 0, position 0.
        at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002c2] in <filename unknown>:0 
        at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00043] in <filename unknown>:0 
        at Newtonsoft.Json.JsonTextReader.Read () [0x00007] in <filename unknown>:0 
        at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, Boolean hasConverter) [0x0003d] in <filename unknown>:0 
        at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) [0x00029] in <filename unknown>:0 
        --- End of inner exception stack trace ---
        at Couchbase.Lite.NewtonsoftJsonSerializer.Deserialize[Object] (System.IO.Stream json) [0x00035] in <filename unknown>:0 
        at Couchbase.Lite.ObjectWriter.ReadValue[Object] (System.IO.Stream jsonStream) [0x00006] in <filename unknown>:0 
        at Couchbase.Lite.ObjectWriter.ReadValue[Object] (IEnumerable`1 json) [0x0000e] in <filename unknown>:0 
        at Couchbase.Lite.Store.SqliteViewStore.FromJSON (IEnumerable`1 json) [0x00017] in <filename unknown>:0

**Comment by borrrden** [comment]
Please file a separate ticket for this issue, along with more information about what is going on, and a longer stack trace if you can get it.

**Comment by reyalpsirc** [comment]
Ok, done :)
