### ISSUE TITLE
Unity.iOS ChangeTracker dying from JSON ArgumentNotNull exception

### ISSUE THREAD

**Issue by z000z** [couchbase/couchbase-lite-net#492]
For some reason this does not happen in the editor version of the Unity Couchbase-lite-net just when trying to run a build in iOS.  I tested this with the Beta 3 release, and also I tried pulling the dll's from the plugins folder of the issue/481 branch and they both run into it.  Here is a snippet of the log from xcode:

ChangeTracker: Making request to http://104.40.17.246:4984/sync_gateway/_changes
ChangeTracker: Waiting for changes feed to finish...
SingleTaskThreadpoolScheduler: Spawning thread for task 3395
   at System.Environment.get_StackTrace()
   at Couchbase.Lite.Util.SingleTaskThreadpoolScheduler.QueueTask(System.Threading.Tasks.Task task)
   at System.Threading.Tasks.Task.Schedule(Boolean throwException)
   at System.Threading.Tasks.TaskContinuation.Execute()
   at System.Threading.Tasks.Task.ProcessCompleteDelegates()
   at System.Threading.Tasks.Task.Finish()
   at System.Threading.Tasks.TaskActionInvoker+ActionTaskInvoke.Invoke(System.Threading.Tasks.Task owner, System.Object state, System.Threading.Tasks.Task context)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.ThreadStart()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.TpScheduler.TaskExecuterCallback(System.Object obj)
ChangeTracker: Getting stream from change tracker response
ChangeTracker: Got stream from change tracker response
ChangeTracker: changed tracker posting change
ChangeTracker: Exception in change tracker
    System.ArgumentNullException: Argument cannot be null.
    Parameter name: method
      at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull (System.Object value, System.String parameterName) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateParametrizedConstructor (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper (System.Object list) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Boolean& createdFromNonDefaultCreator) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <filename unknown>:0 
      at Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType) [0x00000] in <filename unknown>:0 
      at Couchbase.Lite.Replicator.Puller.ChangeTrackerReceivedChange (IDictionary`2 change) [0x00000] in <filename unknown>:0 
      at Couchbase.Lite.Replicator.ChangeTracker.ReceivedChange (IDictionary`2 change) [0x00000] in <filename unknown>:0 
      at Couchbase.Lite.Replicator.ChangeTracker.ReceivedPollResponse (IJsonSerializer jsonReader, Boolean& timedOut) [0x00000] in <filename unknown>:0 
      at Couchbase.Lite.Replicator.ChangeTracker.ChangeFeedResponseHandler (System.Threading.Tasks.Task`1 responseTask) [0x00000] in <filename unknown>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
      at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0 
      at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
      at System.Threading.Tasks.TaskScheduler.TryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
      at Couchbase.Lite.Util.SingleTaskThreadpoolScheduler.<QueueTask>m__0 (System.Object s) [0x00000] in <filename unknown>:0 
      at System.Threading.ParameterizedThreadStart.Invoke (System.Object obj) [0x00000] in <filename unknown>:0

**Comment by borrrden** [comment]
Try adding [this file](https://github.com/couchbase/couchbase-lite-net/blob/master/samples/UnityDemo/Assets/link.xml) to your assets folder.

**Comment by z000z** [comment]
Gave that a shot just now, but looks like I'm still seeing the same issue.  I believe it has something to do with my user document not having anything in the changes field.  The Beta 3 version was outputting the documents to the log and noticed that was empty, not sure if it's supposed to have something in it but all the other documents seemed to have at least 1 value for that field.

**Comment by z000z** [comment]
This is JSON I'm getting back from the call to http://104.40.17.246:4984/sync_gateway/_changes
```
{"results":[
{"seq":4,"id":"_user/unity.user@test.com","changes":[]}
,{"seq":7,"id":"b4008394ae3a4caab255962237433da3","deleted":true,"removed":["unity.user@test.com"],"changes":[{"rev":"2-aa273774e12da69a615eb618a0c4af9e"}]}
,{"seq":8,"id":"9a7c55ae3c31b33a5373966b65c9586e","deleted":true,"removed":["unity.user@test.com"],"changes":[{"rev":"2-ca796be27ebb6d7cc9d056409e19aecf"}]}
],
"last_seq":"8"}
```
I think it may be that first result line since that's the only null I can see there.

**Comment by borrrden** [comment]
What version of Unity are you using?  That is not a "null" but an "empty array".  The error is indicating that the constructor for a type was not found.  If you don't have a relatively new version of Unity then the file I showed will have no effect.  Actually, the iOS version of Couchbase Lite Unity is suffering from IL2CPP issues, and Mono is unusable now because of Apple's requirements.  Pick up the latest 5.1 series patch release if you don't already have it.

**Comment by z000z** [comment]
I'm using the beta 5.2.0f1 Unity version, and with xcode 7 beta 5.  I did notice that if I try to use the ARM64 architecture I get an issue it looks like with some sort of threading area, but ARMv7 or Universal seem to get around that problem atm.

**Comment by borrrden** [comment]
I haven't installed either of the betas yet so I cannot confirm whether or not the fixes that are in the patch version made it into the beta or not.  Is that the latest beta for Unity?

**Comment by z000z** [comment]
Yup it just came out Monday, the first release candidate.

**Comment by borrrden** [comment]
Ok, my time is currently being sucked up by a vicious problem (486) but I will have a look at this after I finish that (not sure how long that will be, unfortunately, but iOS is blocked on 481 anyway).  Just as a note, though, I won't be testing on Xcode 7 until it is officially released.

**Comment by z000z** [comment]
No problem, 486 does look like a nasty one.  I'll continue trying to dig into it and will update here if I find anything that might be helpful or possibly some work around etc.  Thanks!

**Comment by z000z** [comment]
Tracked it down, in Puller ChangeTrackerReceivedChange if you change the line:
```
var changes = change.Get("changes").AsList<object>();
```
to:
```
var changes = change.Get("changes") as Newtonsoft.Json.Linq.JArray;
```
that fixes it for me

**Comment by borrrden** [comment]
Thanks for the clue!  However, I can't use that line because that makes an assumption about the underlying type and the abstraction leaks (we are planning to make the JSON serialization library swappable in the near future).  Perhaps it needs to be changed to `AsList<string>`.

**Comment by z000z** [comment]
Ah ok, that makes sense.  ```AsList<string>``` doesn't work, but I'll see if I can find something else that might, I'll experiment a bit more with it.

**Comment by z000z** [comment]
Found a better fix I believe, you can leave that line ```AsList<object>()``` and instead change the NewtonsoftJsonSerializer class's ```public IList<T> ConvertToList<T>(object obj)``` line 

```return jObj == null ? null : jObj.ToObject<IList<T>>();```
to
```jObj == null ? null : jObj.Select(x => x.ToObject<T>()).ToList();```

**Comment by borrrden** [comment]
Hmmm I'm glad you found a way to work around it!  This line makes me very curious though.  I can't yet reproduce the behavior you mentioned (but I haven't tried it with Unity's runtime yet), and I feel odd about that line (I don't think it has been changed in over a year, if at all and it doesn't make sense why this should fix it).  I'd like to see the error with my own eyes, but since this doesn't seem like it will cause any harm, I will accept it even if I can't reproduce it.

I don't see you in our list of contributors on the repo, though, so have you signed the contributor agreement?

**Comment by z000z** [comment]
Yeah I'm not exactly sure why the iOS build isn't able to go directly the the IList, it's not needed in the editor my guess is possibly there's some sort of reflection happening that lets it work in non iOS builds.  Haven't figured out a good/easy way to debug into that code in the iOS build to see exactly what is going on (had to insert Log outputs and rebuild over and over to track down where the problem was).  

I wasn't in the list of contributors, but just now signed the agreement so hopefully I show up now.
