### ISSUE TITLE
Listener crashes when receiving improper messages

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#590]
As reported in Issue #433

```
System.IO.IOException was unhandled by user code
  HResult=-2146232800
  Message=The handshake failed due to an unexpected packet format.
  Source=System
  StackTrace:
       at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
       at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
       at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
       at WebSocketSharp.Net.HttpConnection.FinishAuth(IAsyncResult result) in C:\Users\S401309\Developer\couchbase-lite-net\src\Couchbase.Lite.Shared\vendor\websocket-sharp\websocket-sharp\Net\HttpConnection.cs:line 172
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
       at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
       at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
       at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
       at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
  InnerException: 
```

**Comment by borrrden** [comment]
So far not able to reproduce this

**Comment by borrrden** [comment]
Note: Possible repro case ->  https://github.com/jamiltz/ListenerSSLExample/

**Comment by borrrden** [comment]
Update to this.  Basic Auth was not the issue, but rather trying to connect to a listener via HTTP when it is listening on HTTPS (and possible vice-versa).  Once I confirm it should be a quick fix.
