### ISSUE TITLE
BadJson doing Peer-2-Peer sync

### ISSUE THREAD

**Issue by chinhnguyen** [couchbase/couchbase-lite-net#677]
Hi Couchbase Team,

I've followed the instruction [here](https://github.com/couchbase/couchbase-lite-net/wiki/Listener-Component) to setup peer-2-peer sync between 2 WPF (4.5) applications.
The 2 can find each other via Bonjour and make connection.
However the sync is not 100% completed after couple of sync.

The log says BadJson - I'm using latest version via Nuget (1.2.1.1)

```
2016-06-24 00:05:23,973 [10] INFO  Willbe.Prism.Log4NetLogger: [Replication] Attempting to start puller (5562212f-ae70-49d7-b89b-3ad6ec23760a)
2016-06-24 00:05:23,973 [20] INFO  Willbe.Prism.Log4NetLogger: [Replication] Attempting to start pusher (f05b95aa-764b-4248-8621-46916024a710)
2016-06-24 00:05:24,069 [10] INFO  Willbe.Prism.Log4NetLogger: [Replication] Beginning replication process...
2016-06-24 00:05:24,075 [10] INFO  Willbe.Prism.Log4NetLogger: [Replication] No local checkpoint, not getting remote one
2016-06-24 00:05:24,127 [20] INFO  Willbe.Prism.Log4NetLogger: [Replication] Beginning replication process...
2016-06-24 00:05:24,127 [20] INFO  Willbe.Prism.Log4NetLogger: [Replication] No local checkpoint, not getting remote one
2016-06-24 00:05:24,449 [20] ERROR Willbe.Prism.Log4NetLogger: [Replication] SendAsyncMultipartDownloaderRequest has an error occurred. - Couchbase.Lite.CouchbaseLiteException: Couchbase Lite error: BadJson ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: Q. Path '', line 2, position 3.
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Couchbase.Lite.NewtonsoftJsonSerializer.Deserialize[T](Stream json)
   --- End of inner exception stack trace ---
   at Couchbase.Lite.NewtonsoftJsonSerializer.Deserialize[T](Stream json)
   at Couchbase.Lite.ObjectWriter.ReadValue[T](Stream jsonStream)
   at Couchbase.Lite.Replication.<SendAsyncMultipartDownloaderRequest>c__AnonStorey5.<>m__0(Task`1 responseMessage)
2016-06-24 00:05:24,451 [20] ERROR Willbe.Prism.Log4NetLogger: [Replication] SendAsyncMultipartDownloaderRequest has an error occurred. - Couchbase.Lite.CouchbaseLiteException: Couchbase Lite error: BadJson ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: v. Path '', line 2, position 5.
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Couchbase.Lite.NewtonsoftJsonSerializer.Deserialize[T](Stream json)
   --- End of inner exception stack trace ---
   at Couchbase.Lite.NewtonsoftJsonSerializer.Deserialize[T](Stream json)
   at Couchbase.Lite.ObjectWriter.ReadValue[T](Stream jsonStream)
   at Couchbase.Lite.Replication.<SendAsyncMultipartDownloaderRequest>c__AnonStorey5.<>m__0(Task`1 responseMessage)
```

I've tried with the latest source code, then the issue seems gone. 
However the code is a bit unstable.

Please help me out, thanks!

**Comment by borrrden** [comment]
We have a release coming up very very soon so let me know what is unstable about the current code so I can fix it :).  

I'm unsure what is going on just from this.  It seems an invalid object is getting returned by the REST request or it's not including the required headers and it is getting accidentally parsed as a JSON object instead of multipart.  Can you see the logs on the "server" side and try to replay one of the requests with Postman or some similar REST API tester?

**Comment by chinhnguyen** [comment]
For the unstable of code on trunk, this is the exception after start syncing

```
System.ObjectDisposedException was unhandled by user code
  HResult=-2146232798
  Message=The CancellationTokenSource has been disposed.
  ObjectName=""
  Source=mscorlib
  StackTrace:
       at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
       at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
       at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
       at System.Threading.CancellationToken.InternalRegisterWithoutEC(Action`1 callback, Object state)
       at System.Threading.CancellationTokenSource.CreateLinkedTokenSource(CancellationToken token1, CancellationToken token2)
       at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
       at Couchbase.Lite.CouchbaseLiteHttpClient.<>c__DisplayClass13_1.<SendAsync>b__0(Task t) in C:\Users\Chinh\Documents\Projects\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication\CouchbaseLiteHttpClient.cs:line 103
       at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: 

```

I'm trying to get more detail for you on the BadJson issue.

**Comment by chinhnguyen** [comment]
This is another different exception (code on trunk)

```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at Couchbase.Lite.CouchbaseLiteHttpClient.<SendAsync>b__13_2(Task`1 t) in C:\Users\Chinh\Documents\Projects\couchbase-lite-net\src\Couchbase.Lite.Shared\Replication\CouchbaseLiteHttpClient.cs:line 117
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: 
       HResult=-2146233029
       Message=A task was canceled.
       InnerException: 

```

**Comment by chinhnguyen** [comment]
Hi Borrrden,

The BadJson does happen on the newest code.

Logs files
[Uploading client-log.txt…](client-log.txt)
and
[Uploading server-log.txt…](server-log.txt)

Please let me know if you need any other information.

**Comment by borrrden** [comment]
How easy is this to reproduce?  Can you provide some steps?  It looks like you are using attachments but the logs appear to have different times.  Can you confirm that these logs are from the same run?

**Comment by chinhnguyen** [comment]
Jim, sorry did'n mention. The 2 machines are on different timezones but
same LAN. I'm trying now with the Peer2Peer testcase to isolate the issue.
Will get you the steps when done. Thanks.

**Comment by chinhnguyen** [comment]
[BadJson.zip](https://github.com/couchbase/couchbase-lite-net/files/339850/BadJson.zip)
Hi Jim,

Sorry for a bit late in replying. I've narrowed down the issue and thought I could figure it by my own.
But it comes to a very weird as in the attachment.
1. The solution has 3 projects - `CBClient`, `CBListener`, and `Kiolyn.Desktop`
2. The `CBListener` will run on a database called `badjson` placed in the `databases` folder
3. The CBCLient and Kiolyn.Desktop share almost everything (packages.json, client cloning code)
But the CBClient can clone successfully while the Kiolyn.Desktop produces the BadJson.

The CBCLient is a console while Kiolyn.Desktop is originally a WPF application.
Been playing around a lot but still not sure what makes the differences.

Please take a look! (just in case, my skype is ngtr9h, please chat any time you like)

**Comment by borrrden** [comment]
I was traveling without a Windows machine when I got this sample, sorry.  Now it had slipped my mind.  I'll download it and give it a try now.

**Comment by borrrden** [comment]
I don't see any mention of badjson when I run the combination of CBListener and the desktop app.  Do you have some steps for me to follow?  Both windows show "Document Count 267" at the end.

**Comment by chinhnguyen** [comment]
@borrrden I simply run the CBListener and then the Kiolyn.Desktop then the error came up.
I've created a github project [here ](https://github.com/chinhnguyen/couchbase-lite-net-badjson) for the sake of experimenting.

Here is the error screen
![badjson](https://cloud.githubusercontent.com/assets/839032/16825387/92bfdd50-499e-11e6-9383-8d22e5351d71.png)

**Comment by chinhnguyen** [comment]
Full logs is here [logs.zip](https://github.com/couchbase/couchbase-lite-net/files/362893/logs.zip)

**Comment by chinhnguyen** [comment]
@borrrden I've dug deeper and here is the result:

The error is happening here in `SendAsyncMultipartDownloaderRequest `of  `Replication `class
`                                if (entity != null) {
                                    try {
                                        var readTask = entity.ReadAsStreamAsync();
                                        //readTask.Wait(); // TODO: This should be scaled based on content length.
                                        inputStream = readTask.Result;
                                        fullBody = Manager.GetObjectMapper().ReadValue<Object>(inputStream);
                                        if (onCompletion != null)
                                            onCompletion(fullBody, error);
                                    } catch (Exception ex) {
                                        Log.To.Sync.W(TAG, "SendAsyncMultipartDownloaderRequest got an exception, aborting...", ex);
                                    } finally {
                                        try {
                                            inputStream.Close();
                                        } catch (Exception) { }
                                    }
                                }
` 

And below is the content inside `inputStream `that is mistakenly treated as JSON:

`\r\n---0EcD7zyCW0qCatCQ6jZE9g\r\nContent-Length: 448\r\nContent-Type: application/json\r\n\r\n{\"_id\":\"it_15121609432745\",\"_rev\":\"1-eb05e9df0b2c486dbb2dd05c438a4d77\",\"category\":\"15121609095809\",\"category_name\":\"Western food\",\"channels\":[\"15121510073220\"],\"hidden\":false,\"id\":\"15121609432745\",\"image\":{\"file\":\"XJlooAeeDrOeq8tkeXkCSnoD\",\"mime\":\"image/png\",\"size\":87327},\"merchantid\":\"15121510073220\",\"modifiers\":[],\"name\":\"Pumpkin soup\",\"ordering\":1,\"price\":8.24,\"type\":\"item\",\"_revisions\":{\"ids\":[\"eb05e9df0b2c486dbb2dd05c438a4d77\"],\"start\":1}}\r\n---0EcD7zyCW0qCatCQ6jZE9g--`

**Comment by chinhnguyen** [comment]
@borrrden , there is a TODO code that seems (to me) that is causing the issue. See `Puller ` class:

        private void PullRemoteRevision(RevisionInternal rev)
        {
            // Construct a query. We want the revision history, and the bodies of attachments that have
            // been added since the latest revisions we have locally.
            // See: http://wiki.apache.org/couchdb/HTTP_Document_API#Getting_Attachments_With_a_Document
            var path = new StringBuilder($"/{Uri.EscapeUriString(rev.DocID)}?rev={Uri.EscapeUriString(rev.RevID.ToString())}&revs=true");

            var attachments = true;
            if(attachments) {
                // TODO: deferred attachments
                path.Append("&attachments=true");
            }


Comment out the last 5 lines to disabled `attachments=true` solve my problem.
My application is not using attachment and not planned to use attachment in the future.
So, IS THIS A GOOD FIX giving the above condition?

**Comment by borrrden** [comment]
It seems like you are missing the `Content-Type` header and that's why the library is mistakenly parsing it as JSON.  Now that I think about it I've seen this happen before.  Are you using a proxy and is it blocking HTTP headers?

**Comment by chinhnguyen** [comment]
@borrrden , looks like these config like is causing the issue

```
  <system.net>
    <requestCaching defaultPolicyLevel="Default" />
  </system.net>
```

Not sure why, so in general it is as below
1. With those configuration lines => the error happens ONLY on my development machine (not yours, not another machine)
2. Without those configuration lines => things work perfect.

Any idea why?

**Comment by borrrden** [comment]
Can't say that I do, but this makes it seem like an environmental issue.  Your request caching default is somehow different than the others.  Perhaps you could replace default with one of the other explicit options?  My guess is that the cache has an invalid response.  Maybe you could try clearing it in Internet Explorer or something?

**Comment by chinhnguyen** [comment]
Yeah! you are right! After cleaning the cache, things works perfectly! 

Thanks for helping!  Let me close this issue - and can't wait to see 1.3 on nuget :-P

**Comment by chinhnguyen** [comment]
Hi @borrrden , is there a good way I can add a timestamp to the request URL so the .net won't cache the request ? 
There is currently no "hook" for caller app to change the URL.
