### ISSUE TITLE
P2P 'server' crashes with large changes set on pull

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#792]
The reported case was with 1.7 million revisions.

**Comment by borrrden** [comment]
This will require a pretty large impact if my theory is correct.  It needs two changes:

1) Don't read all the changes from the DB into memory at once, instead use a generator (as a side effect, the pusher needs a way to consume things lazily...)
2) Don't construct the entire `_changes` response body at once, and instead write to the network stream lazily

**Comment by jonbenedicto** [comment]
As requested, here are the details of this crash. The replication is running between a Windows 10 desktop machine with 16GB of RAM, and a Windows 8 VM with 4GB of RAM. The application is compiled as 32-bit, so only has access to 2GB of RAM.

If WebSocket is disabled on the pull replicator (ReplicationOptions.UseWebSocket = false), the following error occurs on the 'server' end of the pull:

> ERROR) Body: [12] 2016-12-22 09:29:11.111-05:00 Error writing body as pretty JSON, throwing CouchbaseLiteException:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Couchbase.Lite.NewtonsoftJsonSerializer.SerializeObject(Object obj, Boolean pretty) in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Manager\NewtonsoftJsonSerializer.cs:line 93
   at Couchbase.Lite.ObjectWriter.WriteValueAsString[T](T item, Boolean canonical) in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\ObjectWriter.cs:line 97
   at Couchbase.Lite.ObjectWriter.WriteValueAsBytes[T](T item, Boolean canonical) in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\ObjectWriter.cs:line 90
   at Couchbase.Lite.Body.LazyLoadJsonFromObject() in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Documents\Body.cs:line 310

> ERROR) ROUTER (CouchbaseLiteResponse): [12] 2016-12-22 09:29:11.118-05:00 Invalid body on response:
Couchbase.Lite.CouchbaseLiteException: Error writing body as pretty JSON ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Couchbase.Lite.NewtonsoftJsonSerializer.SerializeObject(Object obj, Boolean pretty) in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Manager\NewtonsoftJsonSerializer.cs:line 93
   at Couchbase.Lite.ObjectWriter.WriteValueAsString[T](T item, Boolean canonical) in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\ObjectWriter.cs:line 97
   at Couchbase.Lite.ObjectWriter.WriteValueAsBytes[T](T item, Boolean canonical) in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Util\ObjectWriter.cs:line 90
   at Couchbase.Lite.Body.LazyLoadJsonFromObject() in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Documents\Body.cs:line 310
   --- End of inner exception stack trace ---
   at Couchbase.Lite.Body.LazyLoadJsonFromObject() in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Documents\Body.cs:line 312
   at Couchbase.Lite.Body.AsJson() in D:\Libraries\couchbase-lite-net\src\Couchbase.Lite.Shared\Documents\Body.cs:line 152
   at Couchbase.Lite.Listener.CouchbaseLiteResponse.WriteToContext() in D:\Libraries\couchbase-lite-net\src\ListenerComponent\Couchbase.Lite.Listener.Shared\PeerToPeer\CouchbaseLiteResponse.cs:line 253

> ERROR) ROUTER (CouchbaseLiteRouter): [12] 2016-12-22 09:29:11.118-05:00 Exception writing response:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Couchbase.Lite.Listener.CouchbaseLiteResponse.WriteToContext() in D:\Libraries\couchbase-lite-net\src\ListenerComponent\Couchbase.Lite.Listener.Shared\PeerToPeer\CouchbaseLiteResponse.cs:line 261
   at Couchbase.Lite.Listener.CouchbaseLiteRouter.ProcessResponse(ICouchbaseListenerContext context, ICouchbaseResponseState responseState) in D:\Libraries\couchbase-lite-net\src\ListenerComponent\Couchbase.Lite.Listener.Shared\PeerToPeer\CouchbaseLiteRouter.cs:line 201

If WebSocket is enabled (ReplicationOptions.UseWebSocket = true), then the same error appears in the log, but the 'client' crashes with an error as well:

> 12/22/2016 9:23:13 AM|Fatal|WebSocket.connect:891|WebSocketSharp.WebSocketException: An exception has occurred while reading an HTTP request/response. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
                               at System.IO.MemoryStream.ToArray()
                               at WebSocketSharp.Ext.ReadBytes(Stream stream, Int64 length, Int32 bufferLength) in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\Ext.cs:line 635
                               at WebSocketSharp.HttpBase.readEntityBody(Stream stream, String length) in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\HttpBase.cs:line 113
                               at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout) in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\HttpBase.cs:line 175
                               --- End of inner exception stack trace ---
                               at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout) in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\HttpBase.cs:line 192
                               at WebSocketSharp.HttpRequest.GetResponse(Stream stream, Int32 millisecondsTimeout) in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\HttpRequest.cs:line 160
                               at WebSocketSharp.WebSocket.sendHttpRequest(HttpRequest request, Int32 millisecondsTimeout) in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\WebSocket.cs:line 1539
                               at WebSocketSharp.WebSocket.sendHandshakeRequest() in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\WebSocket.cs:line 1477
                               at WebSocketSharp.WebSocket.doHandshake() in D:\Libraries\couchbase-lite-net\vendor\websocket-sharp\websocket-sharp\WebSocket.cs:line 1011
                               at WebSoc

**Comment by jonbenedicto** [comment]
I did some further debugging and verified that the resulting JSON would end up creating a 170MB byte array. This is apparently running into fragmentation issues with the large object heap, so the application is unable to reserve that much contiguous memory.

**Comment by borrrden** [comment]
This change was quite a bit more finnicky than I thought, but I have an initial implementation of a "streaming" version of this method that will only bring one item into memory at a time as it writes the changes over the network stream.  It's going to be tough to use it for internal logic as well since various things depend on knowing the count of things to process, but for P2P purposes it is hooked up now (on a separate branch for the time being).  It will need to be put through our functional testing suite (attn @sethrosetter ) as well as ported to iOS and Android (@pasin @hideki)

**Comment by borrrden** [comment]
The fix I made here is not valid.  There doesn't appear to be any valid way to sort the changes by sequence unless they are all brought into memory (sorting by sequence at the SQLite level doesn't take into account which revision is current...).

**Comment by borrrden** [comment]
@snej  FYI This is the issue we discussed that needs the "monster query"

**Comment by borrrden** [comment]
Unfortunately 1.x has reached EOL without ever getting a reasonable fix for this.  If it is still an issue on 2.x then please open another issue.
