### ISSUE TITLE
Mono crash with Xamarin Android

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#823]
Using .NET 1.4-46

Failing test - test_replication_with_session_cookie

Full logcat - https://gist.github.com/sethrosetter/4fc90f3308db8be13235b5a1e3aca1c2

```
02-19 22:20:51.561  5292  5347 I mono-stdout: INFO) ROUTER (CouchbaseLiteResponse): [10] 2017-2-19 10:20:51.560-08:00 Response closed
02-19 22:20:51.561  5292  5328 I mono-stdout: INFO) ROUTER (CouchbaseLiteRouter): [6] 2017-2-19 10:20:51.561-08:00 GET /_active_tasks => 200 (ok)
02-19 22:20:51.747  5292  5348 I mono-stdout: INFO) SYNC (Replication): [11] 2017-2-19 10:20:51.747-08:00 Beginning replication process...
02-19 22:20:51.774  5292  5346 F         : * Assertion at /Users/builder/data/lanes/3540/1cf254db/source/mono/mono/metadata/class.c:2387, condition `method->klass == gklass' not met
--------- beginning of crash
02-19 22:20:51.774  5292  5346 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5346 (Thread-2061)
02-19 22:20:51.801  5292  5329 I mono-stdout: INFO) SYNC (Replication): [7] 2017-2-19 10:20:51.801-08:00 Pusher 812b8ef7-7ffd-4748-9444-c740b0a851c4 no local checkpoint, not getting remote one
02-19 22:20:51.885   194   194 I SELinux : SELinux: Loaded file_contexts contexts from /file_contexts.
02-19 22:20:51.888   194   194 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-19 22:20:51.888   194   194 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MMB29K/2419427:user/release-keys'
02-19 22:20:51.888   194   194 F DEBUG   : Revision: '0'
02-19 22:20:51.888   194   194 F DEBUG   : ABI: 'arm'
02-19 22:20:51.888   194   194 F DEBUG   : pid: 5292, tid: 5346, name: Thread-2061  >>> com.couchbase.liteserv <<<
02-19 22:20:51.888   194   194 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-19 22:20:51.908   194   194 F DEBUG   : Abort message: '* Assertion at /Users/builder/data/lanes/3540/1cf254db/source/mono/mono/metadata/class.c:2387, condition `method->klass == gklass' not met
02-19 22:20:51.908   194   194 F DEBUG   : '
02-19 22:20:51.908   194   194 F DEBUG   :     r0 00000000  r1 000014e2  r2 00000006  r3 9f61e978
02-19 22:20:51.908   194   194 F DEBUG   :     r4 9f61e980  r5 9f61e930  r6 00000000  r7 0000010c
02-19 22:20:51.908   194   194 F DEBUG   :     r8 9fa4f770  r9 9dacd844  sl 00000000  fp 00000000
02-19 22:20:51.908   194   194 F DEBUG   :     ip 00000006  sp 9f61d5f0  lr b6d59b61  pc b6d5bf50  cpsr 400e0010
02-19 22:20:51.926   194   194 F DEBUG   : 
02-19 22:20:51.926   194   194 F DEBUG   : backtrace:
02-19 22:20:51.926   194   194 F DEBUG   :     #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
02-19 22:20:51.927   194   194 F DEBUG   :     #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
02-19 22:20:51.927   194   194 F DEBUG   :     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
02-19 22:20:51.927   194   194 F DEBUG   :     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
02-19 22:20:51.927   194   194 F DEBUG   :     #04 pc 000174ac  /system/lib/libc.so (abort+4)
02-19 22:20:51.927   194   194 F DEBUG   :     #05 pc 00227fc4  /data/app/com.couchbase.liteserv-1/lib/arm/libmonosgen-2.0.so
02-19 22:20:52.456   194   194 F DEBUG   : 
02-19 22:20:52.456   194   194 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_00
02-19 22:20:52.456   194   194 E DEBUG   : AM write failed: Broken pipe
02-19 22:20:52.459   780  5391 W ActivityManager:   Force finishing activity com.couchbase.liteserv/.MainActivity
02-19 22:20:52.460   780   799 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
02-19 22:20:52.469   780   972 I WindowState: WIN DEATH: Window{c88611a u0 com.couchbase.liteserv/com.couchbase.liteserv.MainActivity}
02-19 22:20:52.483   780  5391 W ActivityManager: Exception thrown during pause
02-19 22:20:52.483   780  5391 W ActivityManager: android.os.DeadObjectException
02-19 22:20:52.483   780  5391 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
02-19 22:20:52.483   780  5391 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
02-19 22:20:52.486   188   188 E lowmemorykiller: Error writing /proc/5292/oom_score_adj; errno=22
02-19 22:20:52.487   208   208 I Zygote  : Process 5292 exited due to signal (6)
02-19 22:20:52.493   780  5391 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
02-19 22:20:52.507   780  2627 I ActivityManager: Process com.couchbase.liteserv (pid 5292) has died
02-19 22:20:52.565   780   885 I OpenGLRenderer: Initialized EGL, version 1.4
02-19 22:20:52.615 32374  2468 D Index   : Deleting data for locale 'en_US' took 4 millis
02-19 22:20:52.627 32374  2468 D Index   : Indexing locale 'en_US' took 12 millis
02-19 22:20:52.782 32374 32374 D DashboardSummary: rebuildUI took: 91 ms
```

**Comment by djpongh** [comment]
Haven't been able to repro plus the assertion is in Mono code so most likely not us.

**Comment by fruel** [comment]
I can reproduce this when using the same device as @sethrosetter (Nexus 5/hammerhead using Android 6.0.1) using Xamarin with Couchbase Lite 1.4.1. It occurs after some time when pulling a large amount of documents at once (in my test case I replicate 100k documents and it crashes at 20-40k documents completed)

Out of my 3 test devices this issue only occurs on the Nexus 5 (other devices OnePlus 3, Samsung Galaxy XCover 4). @sethrosetter were you able to solve this issue?
