### ISSUE TITLE
Pull replication stopping when coming online

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#824]
Using 1.4-48 .NET, Surface Pro Windows 10 WPF Todo app

Using ec2 cluster with sg 1.4-102, cbs 4.5.1

Steps to repro
1. Go into airplane mode
2. Create a list with tasks
3. Come back online

```
The thread 0x2f88 has exited with code 0 (0x0).
The thread 0x21a0 has exited with code 0 (0x0).
The thread 0x21a4 has exited with code 0 (0x0).
The thread 0x1c34 has exited with code 0 (0x0).
The thread 0x1190 has exited with code 0 (0x0).
The thread 0x297c has exited with code 0 (0x0).
The thread 0x2268 has exited with code 0 (0x0).
The thread 0x17dc has exited with code 0 (0x0).
The thread 0x734 has exited with code 0 (0x0).
INFO) SYNC (NetworkReachabilityManager): [78] 2017-2-21 05:35:10.845-08:00 Network change detected, analyzing connection status...
INFO) SYNC (NetworkReachabilityManager): [78] 2017-2-21 05:35:11.720-08:00 No acceptable IP addresses found, signaling network unreachable
INFO) SYNC (NetworkReachabilityManager): [78] 2017-2-21 05:35:11.733-08:00 Network change detected, analyzing connection status...
INFO) SYNC (Replication): [78] 2017-2-21 05:35:11.736-08:00 Pusher 6c99623b-c427-440e-b08a-9d54317da261 going offline
INFO) SYNC (Replication): [78] 2017-2-21 05:35:11.741-08:00 Puller 6fe485c8-7910-4f68-b94e-2202611a962b going offline
INFO) CHANGE TRACKER (WebSocketChangeTracker): [78] 2017-2-21 05:35:11.742-08:00 WebSocketChangeTracker[todo/] requested to stop
'Training.WPF.vshost.exe' (CLR v4.0.30319: Training.WPF.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Input.Manipulations\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Input.Manipulations.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
INFO) SYNC (NetworkReachabilityManager): [78] 2017-2-21 05:35:11.916-08:00 No acceptable IP addresses found, signaling network unreachable
INFO) CHANGE TRACKER (WebSocketChangeTracker): [78] 2017-2-21 05:35:16.738-08:00 WebSocketChangeTracker[todo/] is closed
The thread 0x179c has exited with code 0 (0x0).
INFO) SYNC (Puller): [23] 2017-2-21 05:35:16.749-08:00 Change tracker for 6fe485c8-7910-4f68-b94e-2202611a962b stopped; error=
INFO) SYNC (Replication): [78] 2017-2-21 05:35:16.758-08:00 6fe485c8-7910-4f68-b94e-2202611a962b: Stop Graceful...
INFO) SYNC (Replication): [23] 2017-2-21 05:35:16.766-08:00 Puller 6fe485c8-7910-4f68-b94e-2202611a962b Stopping
INFO) SYNC (Replication): [78] 2017-2-21 05:35:16.772-08:00 Puller 6fe485c8-7910-4f68-b94e-2202611a962b checkpointing sequence=312
WARN) SYNC (RemoteSession): [78] 2017-2-21 05:35:16.819-08:00 Http Message failed to send, or got error response, passing to callback... http://X.compute-1.amazonaws.com:4984/todo/_local/4b4863081c37f8b45a4ffd13279ac43ed66..., :
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'x.compute-1.amazonaws.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Couchbase.Lite.CouchbaseLiteHttpClient.<SendAsync>c__AnonStorey2.<>m__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'x.compute-1.amazonaws.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Couchbase.Lite.CouchbaseLiteHttpClient.<SendAsync>c__AnonStorey2.<>m__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'x.compute-1.amazonaws.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---
<---

WARN) SYNC (RemoteSession): [78] 2017-2-21 05:35:16.830-08:00   Failed content: <redacted>
WARN) SYNC (Replication): [78] 2017-2-21 05:35:16.832-08:00 Unable to save remote checkpoint for 6fe485c8-7910-4f68-b94e-2202611a962b:
System.Net.WebException: The remote name could not be resolved: 'x.compute-1.amazonaws.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
INFO) SYNC (Replication): [78] 2017-2-21 05:35:16.835-08:00 Puller 6fe485c8-7910-4f68-b94e-2202611a962b stopped.  Elapsed time 6255.553 sec
The thread 0x2bb8 has exited with code 0 (0x0).
The thread 0x1ecc has exited with code 0 (0x0).```

**Comment by borrrden** [comment]
Also on desktop, it looks like another exception needs to be added to the transient list ("The remote name could not be resolved")

**Comment by borrrden** [comment]
This is intermittent as well.  Will push this to 1.4.1.
