### ISSUE TITLE
SyncGateway with Self-Signed Certificate Replication on Android

### ISSUE THREAD

**Issue by rinou92** [couchbase/couchbase-lite-net#864]
Hi,

I'm beginning with Couchbase Lite on Xamarin. I set up and configured a Sync Gateway server with a self-signed SSL certificate. In my mobile app, I have a shared library and a dedicated class to create and start the replications. 

Pull replication is working fine on IOS but on Android, I have the following error:

`Java.Security.Cert.CertPathValidatorException: Trust anchor for certification path not found.
  --- End of managed Java.Security.Cert.CertPathValidatorException stack trace ---
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
	at com.android.okhttp.Connection.connect(Connection.java:143)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)`

I already tried:

`ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;` 

but it had no effect.

According to this article [https://dotnetdevaddict.co.za/2015/07/31/self-signed-certificates-and-xamarin-android/], it's required to create a custom SslSocketFactory and to assign it to the OkHttp client. However, as far as I've seen, these classes are not available/binded in the .Net version.

So, how can I configure the replication to allow self-signed certificates ?

**Comment by borrrden** [comment]
This is new information to me!  Java has this problem and I guess now .NET also has this annoying problem...I'll consult with the Java developer about what to do.

**Comment by borrrden** [comment]
I added an Android specific setting to ReplicationOptions to include a certificate to be trusted.  Once there is a build ready I'll let you know and you can try it to see if it works, if you are still interested in this.

**Comment by borrrden** [comment]
Note that this method might cause all other (even valid) certs to be rejected according to the documentation in [AndroidClientHandler](https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L49-L56) class

**Comment by borrrden** [comment]
Our build server is having issues after we tried to upgrade it.  That's why a build still is not available.

**Comment by borrrden** [comment]
[Build 99](http://latestbuilds.hq.couchbase.com/couchbase-lite-net/1.4.1/99/) should have this API change for Android.

**Comment by borrrden** [comment]
I changed this to be a bool on `ReplicationOptions` to allow self signed certs.  This should only be used in development as it disables most SSL verification.
