### ISSUE TITLE
Database locked exception

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#872]
Using .NET Desktop `2.0.0-b0121` on macOS Sierra. I have a push / pull replication started with Couchbase Sync Gateway/1.5.0(403;8e7a618)

```
// Create docs
var numDocs = 100000;
            Console.WriteLine($"Saving: {numDocs} docs");
            _db.InBatch(() =>
            {
                for (int i = 0; i < numDocs; i++)
                {
                    var doc = new Document($"doc_{i}");
                    doc["random"].Value = Guid.NewGuid().ToString();
                    _db.Save(doc);
                }
            });
```

```
[INFO] DB (Database) [1] 2017-6-9 04:07:23.996-07:00 Opening database at /Users/sethrosetter/Code/mobile-testkit/apps/testkit.net/Testkit.Net.Core/bin/Debug/netcoreapp1.1/CouchbaseLite/in-for-the-long-haul.cblite2
[INFO] SYNC (Replicator) [1] 2017-6-9 04:07:24.053-07:00 Replicator[<*> blip://localhost:4984/db]: Starting
[INFO] SYNC (Replicator) [1] 2017-6-9 04:07:24.074-07:00 Replicator[<*> blip://localhost:4984/db] is Connecting, progress 0/0
[INFO] SYNC (Replicator) [6] 2017-6-9 04:07:24.081-07:00 Replicator[<*> blip://localhost:4984/db] is Connecting, progress 0/0
[INFO] SYNC (WebSocketWrapper) [3] 2017-6-9 04:07:24.152-07:00 WebSocket connecting to localhost:4984
[INFO] SYNC (WebSocketWrapper) [9] 2017-6-9 04:07:24.245-07:00 WebSocket CONNECTED!
[INFO] SYNC (Replicator) [13] 2017-6-9 04:07:24.250-07:00 Replicator[<*> blip://localhost:4984/db] is Busy, progress 0/0
WARN DB (Database) [1] 2017-6-9 04:07:31.204-07:00 Exception during InBatch, rolling back...:
LiteCore.LiteCoreException: LiteCoreException (24): database is locked
   at LiteCore.Interop.NativeHandler.ThrowOrHandle()
   at LiteCore.Interop.NativeHandler.Execute(C4TryLogicDelegate2 block)
   at Couchbase.Lite.Document.SaveInto(C4Document** outDoc, Boolean deletion, IDocumentModel model)
   at Couchbase.Lite.Document.<>c__DisplayClass25_0.<Save>b__0()
   at Couchbase.Lite.Database.<>c__DisplayClass66_0.<InBatch>b__0()
```

**Comment by sethrosetter** [comment]
Also seeing this with that same code block

```
apps/testkit.net [master●] » dotnet run --project Testkit.Net.Core/Testkit.Net.Core.csproj --replication-endpoint "blip://localhost:4984/db" --runtime-min 380
Running Scenario for 380min ...
Replicating with Sync Gateway: blip://localhost:4984/db
Saving: 100000 docs
Replication Activity: Busy
Replication Completed: 0
Replication Total: 0
Replication Activity: Busy
Replication Completed: 0
Replication Total: 0
Updating doc: doc_21515
libc++abi.dylib: terminating with uncaught exception of type char const*
```

**Comment by sethrosetter** [comment]
It requires a continuous push replication to be running before loading the docs.

**Comment by borrrden** [comment]
Happens on Windows too...but not with Objective-C.  I can't quite figure out what is different aside from the GCD mailbox vs threaded mailbox...
