### ISSUE TITLE
.Net Replicator is not replicating

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#880]
_From @Vitaliy-Gorokhovskiy on June 22, 2017 14:19_

Couchbase.Lite Version: 2.0.0-db010
Couchbase.Lite.Support.NetDesktop Version: 2.0.0-db010

private Replicator _replicator;

        var url = new Uri("ws://localhost:4984/db");
           var config = new ReplicatorConfiguration
            {
                Database = _database,
                Target = new ReplicatorTarget(url),
                Continuous = true
            };
            _replicator = new Replicator(config);
            _replicator.Start();

[INFO] DB (Database) [10] 2017-6-22 10:00:26.550-04:00 Opening database at C:\Temp\db.cblite2
[INFO] DB (DB) [10] 2017-6-22 10:00:26.567-04:00 Opening DataFile
[INFO] SYNC (Replicator) [10] 2017-6-22 10:00:26.594-04:00 Replicator[<*> ws://localhost:4984/db]: Starting
[INFO] DB (DB) [10] 2017-6-22 10:00:26.619-04:00 Opening DataFile
[INFO] LITECORE (BLIP) [10] 2017-6-22 10:00:26.621-04:00 {1}--> ->ws:localhost:4984/db/_blipsync
[INFO] LITECORE (BLIP) [10] 2017-6-22 10:00:26.621-04:00 {1} Opening connection...
[INFO] LITECORE (Actor) [10] 2017-6-22 10:00:26.622-04:00 Starting Scheduler<091BDDC0> with 8 threads
[INFO] LITECORE (Actor) [15] 2017-6-22 10:00:26.641-04:00 BLIP[->ws:localhost:4984/db/_blipsync] performNextMessage
[INFO] LITECORE (Actor) [16] 2017-6-22 10:00:26.644-04:00 Repl->ws:localhost:4984/db/_blipsync performNextMessage
[INFO] LITECORE (Actor) [15] 2017-6-22 10:00:26.644-04:00 BLIP[->ws:localhost:4984/db/_blipsync] performNextMessage
[INFO] LITECORE (Actor) [15] 2017-6-22 10:00:26.644-04:00 BLIP[->ws:localhost:4984/db/_blipsync] performNextMessage
[INFO] LITECORE (Actor) [15] 2017-6-22 10:00:26.644-04:00 BLIP[->ws:localhost:4984/db/_blipsync] performNextMessage
[INFO] LITECORE (Actor) [15] 2017-6-22 10:00:26.644-04:00 BLIP[->ws:localhost:4984/db/_blipsync] performNextMessage
[INFO] LITECORE (Actor) [15] 2017-6-22 10:00:26.644-04:00 BLIP[->ws:localhost:4984/db/_blipsync] performNextMessage
[INFO] SYNC (Replicator) [10] 2017-6-22 10:00:26.657-04:00 Replicator[<*> ws://localhost:4984/db] is Connecting, progress 0/0
[INFO] SYNC (Replicator) [19] 2017-6-22 10:00:26.670-04:00 Replicator[<*> ws://localhost:4984/db] is Connecting, progress 0/0
WARN TASK SCHEDULING (SerialQueue) [20] 2017-6-22 10:00:26.712-04:00 Exception during DispatchAsync:
System.ArgumentException: None of the discovered or specified addresses match the socket address family.
Parameter name: context
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.TcpClient.ConnectAsync(String host, Int32 port)
   at Couchbase.Lite.Sync.WebSocketWrapper.<Start>b__25_0()
   at Couchbase.Lite.Support.SerialQueue.ProcessAsync()

_Copied from original issue: couchbase/couchbase-lite-core#160_

**Comment by borrrden** [comment]
_From @snej on June 22, 2017 16:46_

This should have been filed in couchbase-lite-net. @borrrden, any ideas? This looks like it's an issue in .NET code.

**Comment by borrrden** [comment]
Interesting...does 127.0.0.1 work instead of localhost?

**Comment by borrrden** [comment]
It looks like the `TcpClient` class is trying to connect via IPv6 possibly on a network that doesn't support it.  I thought the way I did it would try both but possibly I was wrong and I need to set the `DualMode` property on the underlying socket.
