### ISSUE TITLE
ReplicationChangeEventHandler receives LastError: Java.IO.EOFException

### ISSUE THREAD

**Issue by tura08** [couchbase/couchbase-lite-net#889]
**Version:**
1.4.0 from Nuget

**Device:**
Motorolla Moto G5 Plus
Device OS: Android 7.0

**Authentication method:**
Built in OpenIDConnectAuthenticator

**Problem:**
User is able to sign in properly using the built in OpenIDConnectAuthenticator. However, after a couple of minutes the ReplicationOnChanged handler receives a changed event from the puller where the LastError is _Java.IO.EOFException: Exception of type 'Java.IO.EOFException' was thrown._

**Stack Trace:**
[0:] INFO) CHANGE TRACKER (ChangeTracker): [15] 2017-7-12 10:03:50.347+08:00 SocketChangeTracker[sync_gateway/] Server Version: [: Version=]
[0:] ERROR) NewtonsoftJsonSerializer: [22] 2017-7-12 10:03:50.403+08:00 Error reading from streaming parser, throwing CouchbaseLiteException:
Java.IO.EOFException: Exception of type 'Java.IO.EOFException' was thrown.
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative:ReadZStream (intptr,intptr,int)
  at System.IO.Compression.DeflateStreamNative.ReadZStream (System.IntPtr buffer, System.Int32 length) [0x00000] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.DeflateStream.ReadInternal (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00027] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.DeflateStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00071] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.GZipStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00006] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.StreamReader.ReadBuffer (System.Char[] userBuffer, System.Int32 userOffset, System.Int32 desiredChars, System.Boolean& readToUserBuffer) [0x00039] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.IO.StreamReader.Read (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00082] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at Newtonsoft.Json.JsonTextReader.ReadData (System.Boolean append, System.Int32 charsRequired) [0x00024] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.ReadData (System.Boolean append) [0x00000] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x000f5] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Couchbase.Lite.NewtonsoftJsonSerializer.Read () [0x00000] in /Volumes/Data/jenkins/workspace/couchbase-lite-net-build@2/1.4/Android/couchbase-lite-net/src/Couchbase.Lite.Shared/Util/ContractedDictionary.cs:327 
  --- End of managed Java.IO.EOFException stack trace ---
java.io.EOFException
	at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
[0:] INFO) CHANGE TRACKER (SocketChangeTracker): [22] 2017-7-12 10:03:50.437+08:00 SocketChangeTracker[sync_gateway/] got an exception, analyzing...
[0:] INFO) CHANGE TRACKER (SocketChangeTracker): [22] 2017-7-12 10:03:50.445+08:00 SocketChangeTracker[sync_gateway/] cannot recover, stopping...
[0:] INFO) CHANGE TRACKER (SocketChangeTracker): [22] 2017-7-12 10:03:50.455+08:00 Stopping SocketChangeTracker[sync_gateway/]...
[0:] INFO) SYNC (Puller): [22] 2017-7-12 10:03:50.464+08:00 Change tracker for 816e7ef2-508e-4f57-8234-3e9715c3baf9 stopped; error=Java.IO.EOFException: Exception of type 'Java.IO.EOFException' was thrown.
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative:ReadZStream (intptr,intptr,int)
  at System.IO.Compression.DeflateStreamNative.ReadZStream (System.IntPtr buffer, System.Int32 length) [0x00000] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.DeflateStream.ReadInternal (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00027] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.DeflateStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00071] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.GZipStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00006] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.StreamReader.ReadBuffer (System.Char[] userBuffer, System.Int32 userOffset, System.Int32 desiredChars, System.Boolean& readToUserBuffer) [0x00039] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.IO.StreamReader.Read (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00082] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at Newtonsoft.Json.JsonTextReader.ReadData (System.Boolean append, System.Int32 charsRequired) [0x00024] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.ReadData (System.Boolean append) [0x00000] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x000f5] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Couchbase.Lite.NewtonsoftJsonSerializer.Read () [0x00000] in /Volumes/Data/jenkins/workspace/couchbase-lite-net-build@2/1.4/Android/couchbase-lite-net/src/Couchbase.Lite.Shared/Util/ContractedDictionary.cs:327 
  --- End of managed Java.IO.EOFException stack trace ---
java.io.EOFException
	at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
[0:] INFO) SYNC (Replication): [22] 2017-7-12 10:03:50.472+08:00 Error set during replication (application may continue):
Java.IO.EOFException: Exception of type 'Java.IO.EOFException' was thrown.
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative:ReadZStream (intptr,intptr,int)
  at System.IO.Compression.DeflateStreamNative.ReadZStream (System.IntPtr buffer, System.Int32 length) [0x00000] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.DeflateStream.ReadInternal (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00027] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.DeflateStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00071] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.Compression.GZipStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00006] in <a547bd0d78184f26ab08d022f013c1e1>:0 
  at System.IO.StreamReader.ReadBuffer (System.Char[] userBuffer, System.Int32 userOffset, System.Int32 desiredChars, System.Boolean& readToUserBuffer) [0x00039] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.IO.StreamReader.Read (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00082] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at Newtonsoft.Json.JsonTextReader.ReadData (System.Boolean append, System.Int32 charsRequired) [0x00024] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.ReadData (System.Boolean append) [0x00000] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x000f5] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <9b6398b0b3ae4afdb586fd62eda2ead4>:0 
  at Couchbase.Lite.NewtonsoftJsonSerializer.Read () [0x00000] in /Volumes/Data/jenkins/workspace/couchbase-lite-net-build@2/1.4/Android/couchbase-lite-net/src/Couchbase.Lite.Shared/Util/ContractedDictionary.cs:327 
  --- End of managed Java.IO.EOFException stack trace ---
java.io.EOFException
	at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)

**Comment by borrrden** [comment]
Looks like switching to the Android http client handler is causing me a lot of grief.  The library won't recognize this exception, but it means (I think) that the other side hung up.  This is socket mode so it should cause a retry but it's not.  For now you will have to tell the replication to start up again when this error happens.
