### ISSUE TITLE
Getting exception when starting the replication on .net

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#955]
I'm getting exception when starting replication. 

```
Error in handler for http://172.23.121.73:55555/replicator_start: The type initializer for 'Couchbase.Lite.Sync.HTTPLogic' threw an exception.
InnerException	{System.EntryPointNotFoundException: Unable to find an entry point named 'c4_getVersion' in DLL 'LiteCore'.
   at LiteCore.Interop.NativeRaw.c4_getVersion()
   at LiteCore.Interop.Native.c4_getVersion() in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\vendor\couchbase-lite-core\CSharp\src\LiteCore.Shared\Interop\C4Base_native.cs:line 116
   at Couchbase.Lite.Sync.HTTPLogic.GetUserAgent() in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\src\Couchbase.Lite\Sync\HTTPLogic.cs:line 238
   at Couchbase.Lite.Sync.HTTPLogic..cctor() in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\src\Couchbase.Lite\Sync\HTTPLogic.cs:line 48}	System.Exception {System.EntryPointNotFoundException}
```

I'm attaching an image showing the replicator configuration before the execution of replicator.start() method.
<img width="1440" alt="screenshot 2018-02-02 19 07 16" src="https://user-images.githubusercontent.com/18100038/35737727-87ec4eb2-0852-11e8-92f6-dca909f7fd97.png">

This is replication configuration method.

```
        public static void Configure([NotNull] NameValueCollection args,
                                                     [NotNull] IReadOnlyDictionary<string, object> postBody,
                                                     [NotNull] HttpListenerResponse response)
        {
            ReplicatorConfiguration config = null;
            
            With<Database>(postBody, "source_db", sdb =>
            {
                if (postBody.ContainsKey("target_url"))
                {
                    Uri uri = new Uri(postBody["target_url"].ToString());
                    URLEndpoint targetUrl =  new URLEndpoint(uri);
                    config = new ReplicatorConfiguration(sdb, targetUrl);
                }
                else if (postBody.ContainsKey("target_db"))
                {
                    With<Database>(postBody, "target_db", tdb =>
                    {
                        DatabaseEndpoint dbEndPoint = new DatabaseEndpoint(tdb);
                        config = new ReplicatorConfiguration(sdb, dbEndPoint);
                    });
                }
                else
                {
                    throw new Exception("Illegal arguments provided");
                }
                if (postBody.ContainsKey("continous"))
                {
                    config.Continuous = Convert.ToBoolean(postBody["continous"]);
                }
                if (postBody.ContainsKey("channels"))
                {
                    config.Channels = (List<string>) postBody["channels"];
                }
                if (postBody.ContainsKey("documentIds"))
                {
                    config.DocumentIDs = (List<string>)postBody["documentIds"]; ;
                }
                if (postBody.ContainsKey("authenticator"))
                {
                    Authenticator authenticator = MemoryMap.Get<Authenticator>(postBody["authenticator"].ToString());
                    config.Authenticator = authenticator;
                }
                if (postBody.ContainsKey("conflictResolver"))
                {
                    IConflictResolver conflictResolver = MemoryMap.Get<IConflictResolver>(postBody["conflictResolver"].ToString());
                    config.ConflictResolver = conflictResolver;
                }

                if (postBody.ContainsKey("headers"))
                {
                    Dictionary<String, String> headers = (Dictionary<String, String>)postBody["headers"];
                    config.Headers = headers;
                }

                if (postBody.ContainsKey("replicatorType"))
                {
                    var replicatorType = postBody["replication_type"].ToString().ToLower();
                    if (replicatorType == "push")
                    {
                        config.ReplicatorType = ReplicatorType.Push;
                    }
                    else if (replicatorType == "pull")
                    {
                        config.ReplicatorType = ReplicatorType.Pull;
                    }
                    else
                    {
                        config.ReplicatorType = ReplicatorType.PushAndPull;
                    }
                }
                response.WriteBody(MemoryMap.Store(config));
            });
        }
```

This is Replication start method

```
        public static void StartReplication([NotNull] NameValueCollection args,
            [NotNull] IReadOnlyDictionary<string, object> postBody,
            [NotNull] HttpListenerResponse response)
        {
            With<Replicator>(postBody, "replicator", r =>
            {
                r.Start();
                response.WriteEmptyBody();
            });
        }
```

**Comment by borrrden** [comment]
This is because the TestServer.NetCore project is still using db021.  When you update the packages you need to make sure that you update the Couchbase packages on *all* of the projects you are running.

**Comment by hrajput89** [comment]
Able to start the replication after updating TestServer.NetCore project too to DB22
