### ISSUE TITLE
replication does not go from idle to stopped state with test_no_conflicts_update_with_revs_limit

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#992]
### Builds
.net b0636, server 5.1.0-5552, sync-gateway 2.0.0-823

### Test ran
```
pytest -s --mode=cc --server-version=5.1.0-5552 --sync-gateway-version=2.0.0-823 --liteserv-platform=net-msft --liteserv-host=192.168.1.2 --liteserv-port=8080  --xattrs --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py --liteserv-version=2.0.0-b0636 --no-conflicts --skip-provisioning -k 'test_no_conflicts_update_with_revs_limit'
```
This test passed with .net build 0611.
It passes with ios build 702

### Actual
The test fails trying to stop the replicator, replicator is always in the idle state after SG restarts.

### CBL logs
```
INFO) Sync {Repl#11466} now busy
INFO) LiteCore {C4SocketImpl#11590}==> class litecore::websocket::C4SocketImpl ws:192.168.33.22:4984/db/_blipsync
INFO) LiteCore {C4SocketImpl#11590} Requesting close with status=1000, message=''
INFO) Sync (Replicator) [21] 2018-03-12T18:27:13.0579329-07:00 Replicator[*> ws://192.168.33.22:4984/db] is Busy, progress 58580/58580
INFO) Sync (WebSocketWrapper) [366] 2018-03-12T18:27:13.1665091-07:00 WebSocket CLOSED WITH ERROR: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Couchbase.Lite.Sync.WebSocketWrapper.PerformRead()
WARNING) LiteCore {C4SocketImpl#11590} Unexpected or unclean socket disconnect! (reason=errno, code=54)
INFO) LiteCore {C4SocketImpl#11590} sent 28139 bytes, rcvd 4037, in 57.841 sec (486/sec, 70/sec)
INFO) LiteCore {Connection#11465} Closed with errno 54: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
INFO) Sync {Repl#11466} Connection closed with errno 54: "Unable to read data from the transport connection: An established connection was aborted by the software in your host machine." (state=3)
ERROR) Sync {Repl#11466} Got LiteCore error: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. (2/54)
VERBOSE) Sync {Repl#11466} progress +0/+0, 0 docs -- now 58580 / 58580, 310 docs
```

**Comment by raghusarangapani** [comment]
Verified with .net b0647, server 5.1.0-5552, sync-gateway 2.0.0-823:
Test passes.
